package org.toughradius.model;

public class RadBlacklist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_BLACKLIST.MACADDR
     *
     * @mbggenerated Sat Aug 31 00:46:14 CST 2013
     */
    private String macaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_BLACKLIST.EXPIRE
     *
     * @mbggenerated Sat Aug 31 00:46:14 CST 2013
     */
    private Integer expire;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_BLACKLIST.MACADDR
     *
     * @return the value of RAD_BLACKLIST.MACADDR
     *
     * @mbggenerated Sat Aug 31 00:46:14 CST 2013
     */
    public String getMacaddr() {
        return macaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_BLACKLIST.MACADDR
     *
     * @param macaddr the value for RAD_BLACKLIST.MACADDR
     *
     * @mbggenerated Sat Aug 31 00:46:14 CST 2013
     */
    public void setMacaddr(String macaddr) {
        this.macaddr = macaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_BLACKLIST.EXPIRE
     *
     * @return the value of RAD_BLACKLIST.EXPIRE
     *
     * @mbggenerated Sat Aug 31 00:46:14 CST 2013
     */
    public Integer getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_BLACKLIST.EXPIRE
     *
     * @param expire the value for RAD_BLACKLIST.EXPIRE
     *
     * @mbggenerated Sat Aug 31 00:46:14 CST 2013
     */
    public void setExpire(Integer expire) {
        this.expire = expire;
    }
}