package org.toughradius.model;

public class RadClient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_CLIENT.ADDRESS
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_CLIENT.SECRET
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String secret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_CLIENT.CLIENT_DESC
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String clientDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_CLIENT.ADDRESS
     *
     * @return the value of RAD_CLIENT.ADDRESS
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_CLIENT.ADDRESS
     *
     * @param address the value for RAD_CLIENT.ADDRESS
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_CLIENT.SECRET
     *
     * @return the value of RAD_CLIENT.SECRET
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_CLIENT.SECRET
     *
     * @param secret the value for RAD_CLIENT.SECRET
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setSecret(String secret) {
        this.secret = secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_CLIENT.CLIENT_DESC
     *
     * @return the value of RAD_CLIENT.CLIENT_DESC
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getClientDesc() {
        return clientDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_CLIENT.CLIENT_DESC
     *
     * @param clientDesc the value for RAD_CLIENT.CLIENT_DESC
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setClientDesc(String clientDesc) {
        this.clientDesc = clientDesc;
    }
}