package org.toughradius.model;

import java.io.Serializable;

public class RadClient implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_CLIENT.ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_CLIENT.SECRET
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String secret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_CLIENT.CLIENT_DESC
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String clientDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_CLIENT.CLIENT_TYPE
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RAD_CLIENT
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_CLIENT.ADDRESS
     *
     * @return the value of RAD_CLIENT.ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_CLIENT.ADDRESS
     *
     * @param address the value for RAD_CLIENT.ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_CLIENT.SECRET
     *
     * @return the value of RAD_CLIENT.SECRET
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_CLIENT.SECRET
     *
     * @param secret the value for RAD_CLIENT.SECRET
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setSecret(String secret) {
        this.secret = secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_CLIENT.CLIENT_DESC
     *
     * @return the value of RAD_CLIENT.CLIENT_DESC
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getClientDesc() {
        return clientDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_CLIENT.CLIENT_DESC
     *
     * @param clientDesc the value for RAD_CLIENT.CLIENT_DESC
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setClientDesc(String clientDesc) {
        this.clientDesc = clientDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_CLIENT.CLIENT_TYPE
     *
     * @return the value of RAD_CLIENT.CLIENT_TYPE
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_CLIENT.CLIENT_TYPE
     *
     * @param clientType the value for RAD_CLIENT.CLIENT_TYPE
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAD_CLIENT
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", address=").append(address);
        sb.append(", secret=").append(secret);
        sb.append(", clientDesc=").append(clientDesc);
        sb.append(", clientType=").append(clientType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}