package org.toughradius.model;

public class RadGroupMetaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_GROUP_META.GROUP_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_GROUP_META.NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_GROUP_META.GROUP_NAME
     *
     * @return the value of RAD_GROUP_META.GROUP_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_GROUP_META.GROUP_NAME
     *
     * @param groupName the value for RAD_GROUP_META.GROUP_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_GROUP_META.NAME
     *
     * @return the value of RAD_GROUP_META.NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_GROUP_META.NAME
     *
     * @param name the value for RAD_GROUP_META.NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }
}