package org.toughradius.model;

import java.io.Serializable;

public class RadGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_GROUP.GROUP_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_GROUP.GROUP_DESC
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String groupDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RAD_GROUP
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_GROUP.GROUP_NAME
     *
     * @return the value of RAD_GROUP.GROUP_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_GROUP.GROUP_NAME
     *
     * @param groupName the value for RAD_GROUP.GROUP_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_GROUP.GROUP_DESC
     *
     * @return the value of RAD_GROUP.GROUP_DESC
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getGroupDesc() {
        return groupDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_GROUP.GROUP_DESC
     *
     * @param groupDesc the value for RAD_GROUP.GROUP_DESC
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAD_GROUP
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupName=").append(groupName);
        sb.append(", groupDesc=").append(groupDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}