package org.toughradius.model;

public class RadGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_GROUP.GROUP_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_GROUP.GROUP_DESC
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String groupDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_GROUP.GROUP_NAME
     *
     * @return the value of RAD_GROUP.GROUP_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_GROUP.GROUP_NAME
     *
     * @param groupName the value for RAD_GROUP.GROUP_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_GROUP.GROUP_DESC
     *
     * @return the value of RAD_GROUP.GROUP_DESC
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getGroupDesc() {
        return groupDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_GROUP.GROUP_DESC
     *
     * @param groupDesc the value for RAD_GROUP.GROUP_DESC
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }
}