package org.toughradius.model;

public class RadGroupMeta extends RadGroupMetaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_GROUP_META.VALUE
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_GROUP_META.VALUE
     *
     * @return the value of RAD_GROUP_META.VALUE
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_GROUP_META.VALUE
     *
     * @param value the value for RAD_GROUP_META.VALUE
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setValue(String value) {
        this.value = value;
    }
}