package org.toughradius.model;

import java.io.Serializable;

public class RadOnlineKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_ONLINE.CLIENT_ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String clientAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_ONLINE.SESSION_ID
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RAD_ONLINE
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_ONLINE.CLIENT_ADDRESS
     *
     * @return the value of RAD_ONLINE.CLIENT_ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getClientAddress() {
        return clientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_ONLINE.CLIENT_ADDRESS
     *
     * @param clientAddress the value for RAD_ONLINE.CLIENT_ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setClientAddress(String clientAddress) {
        this.clientAddress = clientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_ONLINE.SESSION_ID
     *
     * @return the value of RAD_ONLINE.SESSION_ID
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_ONLINE.SESSION_ID
     *
     * @param sessionId the value for RAD_ONLINE.SESSION_ID
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAD_ONLINE
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clientAddress=").append(clientAddress);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}