package org.toughradius.model;

import java.io.Serializable;

public class RadOnline extends RadOnlineKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_ONLINE.USER_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_ONLINE.IP_ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_ONLINE.MAC_ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String macAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_ONLINE.ACCT_START
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String acctStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_ONLINE.NAS_PORT
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String nasPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RAD_ONLINE
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_ONLINE.USER_NAME
     *
     * @return the value of RAD_ONLINE.USER_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_ONLINE.USER_NAME
     *
     * @param userName the value for RAD_ONLINE.USER_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_ONLINE.IP_ADDRESS
     *
     * @return the value of RAD_ONLINE.IP_ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_ONLINE.IP_ADDRESS
     *
     * @param ipAddress the value for RAD_ONLINE.IP_ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_ONLINE.MAC_ADDRESS
     *
     * @return the value of RAD_ONLINE.MAC_ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getMacAddress() {
        return macAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_ONLINE.MAC_ADDRESS
     *
     * @param macAddress the value for RAD_ONLINE.MAC_ADDRESS
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_ONLINE.ACCT_START
     *
     * @return the value of RAD_ONLINE.ACCT_START
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getAcctStart() {
        return acctStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_ONLINE.ACCT_START
     *
     * @param acctStart the value for RAD_ONLINE.ACCT_START
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setAcctStart(String acctStart) {
        this.acctStart = acctStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_ONLINE.NAS_PORT
     *
     * @return the value of RAD_ONLINE.NAS_PORT
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getNasPort() {
        return nasPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_ONLINE.NAS_PORT
     *
     * @param nasPort the value for RAD_ONLINE.NAS_PORT
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setNasPort(String nasPort) {
        this.nasPort = nasPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAD_ONLINE
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", ipAddress=").append(ipAddress);
        sb.append(", macAddress=").append(macAddress);
        sb.append(", acctStart=").append(acctStart);
        sb.append(", nasPort=").append(nasPort);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}