package org.toughradius.model;

public class RadUserMetaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER_META.USER_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER_META.NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER_META.USER_NAME
     *
     * @return the value of RAD_USER_META.USER_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER_META.USER_NAME
     *
     * @param userName the value for RAD_USER_META.USER_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER_META.NAME
     *
     * @return the value of RAD_USER_META.NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER_META.NAME
     *
     * @param name the value for RAD_USER_META.NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }
}