package org.toughradius.model;

import java.io.Serializable;

public class RadUserMeta extends RadUserMetaKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER_META.VALUE
     *
     * @mbggenerated Sun Sep 01 20:56:17 CST 2013
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RAD_USER_META
     *
     * @mbggenerated Sun Sep 01 20:56:17 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER_META.VALUE
     *
     * @return the value of RAD_USER_META.VALUE
     *
     * @mbggenerated Sun Sep 01 20:56:17 CST 2013
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER_META.VALUE
     *
     * @param value the value for RAD_USER_META.VALUE
     *
     * @mbggenerated Sun Sep 01 20:56:17 CST 2013
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAD_USER_META
     *
     * @mbggenerated Sun Sep 01 20:56:17 CST 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", value=").append(value);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}