package org.toughradius.model;

public class RadUserMeta extends RadUserMetaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER_META.VALUE
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER_META.VALUE
     *
     * @return the value of RAD_USER_META.VALUE
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER_META.VALUE
     *
     * @param value the value for RAD_USER_META.VALUE
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setValue(String value) {
        this.value = value;
    }
}