package org.toughradius.model;

public class RadUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER.USER_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER.PASSWORD
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER.GROUP_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER.USER_NAME
     *
     * @return the value of RAD_USER.USER_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER.USER_NAME
     *
     * @param userName the value for RAD_USER.USER_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER.PASSWORD
     *
     * @return the value of RAD_USER.PASSWORD
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER.PASSWORD
     *
     * @param password the value for RAD_USER.PASSWORD
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER.GROUP_NAME
     *
     * @return the value of RAD_USER.GROUP_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER.GROUP_NAME
     *
     * @param groupName the value for RAD_USER.GROUP_NAME
     *
     * @mbggenerated Fri Aug 30 21:38:13 CST 2013
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
}