package org.toughradius.model;

import java.io.Serializable;

public class RadUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER.USER_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER.PASSWORD
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAD_USER.GROUP_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RAD_USER
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER.USER_NAME
     *
     * @return the value of RAD_USER.USER_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER.USER_NAME
     *
     * @param userName the value for RAD_USER.USER_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER.PASSWORD
     *
     * @return the value of RAD_USER.PASSWORD
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER.PASSWORD
     *
     * @param password the value for RAD_USER.PASSWORD
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAD_USER.GROUP_NAME
     *
     * @return the value of RAD_USER.GROUP_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAD_USER.GROUP_NAME
     *
     * @param groupName the value for RAD_USER.GROUP_NAME
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAD_USER
     *
     * @mbggenerated Sun Sep 01 00:11:50 CST 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", groupName=").append(groupName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}