create table RAD_USER
(
    USER_NAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    GROUP_NAME VARCHAR(64) NOT NULL
);
alter table RAD_USER add constraint PK_RAD_USER primary key (USER_NAME);

create table RAD_USER_META
(
    USER_NAME VARCHAR(64) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    DESC VARCHAR(512) 
);
alter table RAD_USER_META add constraint PK_RAD_USER_META primary key (USER_NAME,NAME);


create table RAD_GROUP
(
    GROUP_NAME VARCHAR(64) NOT NULL,
    GROUP_DESC VARCHAR(255) NOT NULL
);
alter table RAD_GROUP add constraint PK_RAD_GROUP primary key (GROUP_NAME);

create table RAD_GROUP_META
(
    GROUP_NAME VARCHAR(64) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    DESC VARCHAR(512) 
);
alter table RAD_GROUP_META add constraint PK_RAD_GROUP_META primary key (GROUP_NAME,NAME);

create table RAD_CLIENT
(
    ADDRESS VARCHAR(128) NOT NULL,
    SECRET VARCHAR(128) NOT NULL,
    CLIENT_DESC VARCHAR(255) NOT NULL,
    CLIENT_TYPE VARCHAR(255) NOT NULL
);
alter table RAD_CLIENT add constraint PK_RAD_CLIENT primary key (ADDRESS);

create table RAD_ADMIN
(
    LOGIN_NAME VARCHAR(128) NOT NULL,
    PASSWORD  VARCHAR(128) NOT NULL
);
alter table RAD_ADMIN add constraint PK_RAD_ADMIN primary key (LOGIN_NAME);

create table RAD_ONLINE
(
    USER_NAME VARCHAR(128) NOT NULL,
    CLIENT_ADDRESS  VARCHAR(128) NOT NULL,
    SESSION_ID  VARCHAR(128) NOT NULL,
    IP_ADDRESS  VARCHAR(128) NOT NULL,
    MAC_ADDRESS  VARCHAR(128) NOT NULL,
    ACCT_START  VARCHAR(128) NOT NULL,
    NAS_PORT  VARCHAR(512) NOT NULL,
    START_SOURCE  INTEGER
);
alter table RAD_ONLINE add constraint PK_RAD_ONLINE primary key (CLIENT_ADDRESS,SESSION_ID);
